# Generated by Django 5.1.2 on 2024-12-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_uservote"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
